"""add_use_trocr_to_dietary_profiles

Revision ID: 886b257bad8e
Revises: 
Create Date: 2026-03-21 21:31:42.358110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '886b257bad8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'dietary_profiles',
        sa.Column('use_trocr', sa.Boolean(), nullable=True, server_default=sa.text('false')),
    )
    # Backfill any existing rows that got NULL (pre-server_default)
    op.execute("UPDATE dietary_profiles SET use_trocr = false WHERE use_trocr IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dietary_profiles', 'use_trocr')
    # ### end Alembic commands ###
